# Generated by Django 4.0.4 on 2022-05-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Royal Hotel', max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('bedroom', models.SmallIntegerField(verbose_name='Односпальная комната')),
                ('bedrooms', models.SmallIntegerField(verbose_name='Двуспальная комната')),
                ('parking', models.CharField(help_text='Платная', max_length=255, verbose_name='Стоимость парковки')),
                ('swimming', models.CharField(help_text='Есть', max_length=255, verbose_name='Бассейн')),
            ],
        ),
    ]
