# Generated by Django 4.0.4 on 2022-05-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('logo', models.ImageField(upload_to='logo/')),
                ('phone', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
    ]
