# Generated by Django 4.0.4 on 2022-05-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='email',
            field=models.CharField(help_text='example@gmail.com', max_length=255, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='logo',
            field=models.ImageField(upload_to='logo/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='phone',
            field=models.CharField(help_text='0707070707', max_length=250, verbose_name='Телефон номер'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title',
            field=models.CharField(help_text='BookingKG', max_length=250, verbose_name='Название'),
        ),
    ]
